"""
Django settings for lampisite project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+9izsa4uze%_ia@!6j@v(%hp6tcag)9cguo7z1h&r%mi7d$f1c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'lampi.apps.LampiConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lampisite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lampisite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # nopep8
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # nopep8
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # nopep8
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # nopep8
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "static")

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login'

DEFAULT_USER = 'parked_device_user'

KEEN_CREDENTIALS = {
    'project_id': '5ab9c9b1c9e77c00016932bb',
    'write_key': '715A0B7DEAA46556F391BA758322EF06584A62CF496E9076D50D5427EA388061D9685C428D8E8865349395DF2D114FFA8623F002E60E9C163F7F7AA4C9A6200C7E5D8E36226EA27780BABFFE1522118F9A8A9BA892A2B0DD82A016608B838095',
    'read_key': 'E984547E7C21C0C15E71DDF6E46BA96F915FED1DCFA8F876B0DE615E45828E768833BBC3D46675648ACEBB136CA535FD5770E4CD3C016B04284F923B91473AACD9AD631A29BE8E4719A656134979985F6B8149CB002367326E58B60964C91EDE',
}
